SEO_PAGES = {
    "inventory-management-for-repair-shops": {
        "tier": "Tier 1",
        "keyword": "inventory management for repair shops",
        "audience": "repair shops",
        "title": "Inventory Management for Repair Shops | CountDepot",
        "description": "Track parts, tools, jobs, and repair inventory without paying enterprise software prices.",
        "hero": "Inventory management built for repair shops that need parts, tools, and jobs under control.",
        "pain": "Repair shops lose margin when parts disappear, job materials are not reserved, or techs waste time asking what is in stock.",
        "use_cases": ["Track parts by shelf, SKU, vendor, or serial number", "Reserve parts for upcoming jobs", "Check tools in and out by technician", "Spot low-stock supplies before jobs get delayed"],
    },
    "inventory-software-for-nonprofits": {
        "tier": "Tier 1",
        "keyword": "inventory software for nonprofits",
        "audience": "nonprofits",
        "title": "Inventory Software for Nonprofits | CountDepot",
        "description": "Affordable inventory software for nonprofits tracking donated goods, equipment, supplies, and locations.",
        "hero": "Simple inventory software for nonprofits managing donations, supplies, and shared equipment.",
        "pain": "Nonprofits need accountability without complex systems, expensive seats, or manual spreadsheets that fall apart during busy donation cycles.",
        "use_cases": ["Track donated goods by category and location", "Assign equipment to staff or programs", "Keep audit-friendly item history", "Manage supplies across storage rooms and sites"],
    },
    "inventory-management-for-photographers": {
        "tier": "Tier 1",
        "keyword": "inventory management for photographers",
        "audience": "photographers",
        "title": "Inventory Management for Photographers | CountDepot",
        "description": "Track cameras, lenses, lights, batteries, cases, and rented gear with CountDepot.",
        "hero": "Gear tracking for photographers who need to know where every camera, lens, and light is.",
        "pain": "Photography gear is expensive, portable, and easy to misplace between shoots, assistants, storage, and rentals.",
        "use_cases": ["Track cameras, lenses, lights, cases, and batteries", "Check gear out for shoots", "Reserve equipment for upcoming jobs", "Record serial numbers and condition notes"],
    },
    "inventory-tracking-for-restaurants": {
        "tier": "Tier 1",
        "keyword": "inventory tracking for restaurants",
        "audience": "restaurants",
        "title": "Inventory Tracking for Restaurants | CountDepot",
        "description": "Track restaurant supplies, equipment, dry goods, and stock movement without bloated systems.",
        "hero": "Restaurant inventory tracking for teams that need supply visibility without enterprise overhead.",
        "pain": "Restaurants move fast, and missing supplies or equipment create delays, waste, and rushed buying decisions.",
        "use_cases": ["Track food supplies, disposables, and equipment", "Monitor low-stock items", "Organize inventory by storage area", "Record cost and supplier details"],
    },
    "inventory-software-for-churches": {
        "tier": "Tier 1",
        "keyword": "inventory software for churches",
        "audience": "churches",
        "title": "Inventory Software for Churches | CountDepot",
        "description": "Church inventory software for equipment, donations, supplies, rooms, and ministry assets.",
        "hero": "Inventory software for churches managing equipment, donations, and ministry supplies.",
        "pain": "Church assets are often shared by volunteers, ministries, rooms, and events, which makes spreadsheets hard to keep accurate.",
        "use_cases": ["Track AV gear, furniture, supplies, and donations", "Assign items to rooms, ministries, or people", "Reserve equipment for events", "Keep item history for accountability"],
    },
    "inventory-management-for-gyms": {
        "tier": "Tier 1",
        "keyword": "inventory management for gyms",
        "audience": "gyms",
        "title": "Inventory Management for Gyms | CountDepot",
        "description": "Track gym equipment, supplies, maintenance items, and locations with affordable inventory software.",
        "hero": "Inventory management for gyms that need equipment, supplies, and maintenance items organized.",
        "pain": "Gyms need to track high-use equipment and supplies without slowing down front-desk or operations staff.",
        "use_cases": ["Track equipment by area or condition", "Monitor cleaning and retail supplies", "Record maintenance notes", "Assign assets to sites or rooms"],
    },
    "inventory-software-for-auto-detailing": {
        "tier": "Tier 1",
        "keyword": "inventory software for auto detailing",
        "audience": "auto detailing businesses",
        "title": "Inventory Software for Auto Detailing | CountDepot",
        "description": "Track detailing chemicals, tools, towels, machines, and supplies without spreadsheet chaos.",
        "hero": "Inventory software for auto detailing teams tracking products, tools, and supplies.",
        "pain": "Detailing margins depend on knowing what products are available, what needs reordering, and where tools are being used.",
        "use_cases": ["Track chemicals, pads, towels, tools, and machines", "Monitor low-stock consumables", "Organize inventory by van, shelf, or shop", "Record costs for supply planning"],
    },
    "inventory-tracking-for-veterinary-clinics": {
        "tier": "Tier 1",
        "keyword": "inventory tracking for veterinary clinics",
        "audience": "veterinary clinics",
        "title": "Inventory Tracking for Veterinary Clinics | CountDepot",
        "description": "Track veterinary supplies, equipment, consumables, and clinic inventory with CountDepot.",
        "hero": "Inventory tracking for veterinary clinics that need clear supply and equipment visibility.",
        "pain": "Clinics need fast access to supplies and equipment information without relying on scattered notes or manual counts.",
        "use_cases": ["Track supplies, equipment, and consumables", "Organize inventory by room or storage area", "Monitor low-stock clinic items", "Keep audit history for item movement"],
    },
    "inventory-management-for-it": {
        "tier": "Tier 2",
        "keyword": "inventory management for IT departments",
        "audience": "IT departments",
        "title": "Inventory Management for IT Departments | CountDepot",
        "description": "Affordable IT inventory management for laptops, network gear, accessories, and user assignments.",
        "hero": "Inventory management for IT departments tracking devices, accessories, and assignments.",
        "pain": "IT teams need asset accountability without paying for oversized platforms before the process is mature.",
        "use_cases": ["Track laptops, monitors, switches, and accessories", "Assign items to users or locations", "Record serial numbers and condition", "See checkout history and ownership"],
    },
    "inventory-software-for-schools": {
        "tier": "Tier 2",
        "keyword": "inventory software for schools",
        "audience": "schools",
        "title": "Inventory Software for Schools | CountDepot",
        "description": "Budget-conscious inventory software for school equipment, supplies, classrooms, and departments.",
        "hero": "Inventory software for schools that need equipment and supplies organized by room, department, or user.",
        "pain": "Schools manage many shared assets with limited staff time and tight budgets.",
        "use_cases": ["Track classroom equipment and supplies", "Assign assets to rooms or staff", "Manage shared devices and AV equipment", "Keep clean item history for audits"],
    },
    "inventory-tracking-for-rental": {
        "tier": "Tier 2",
        "keyword": "inventory tracking for rental companies",
        "audience": "rental companies",
        "title": "Inventory Tracking for Rental Companies | CountDepot",
        "description": "Track rental items, availability, checkouts, reservations, and returns with CountDepot.",
        "hero": "Inventory tracking for rental companies with fast checkouts, returns, and reservations.",
        "pain": "Rental companies lose revenue when item availability is unclear or returns are not updated quickly.",
        "use_cases": ["Check rental items in and out", "Reserve items for future jobs", "Track quantity available versus reserved", "Record condition and return notes"],
    },
    "inventory-management-for-construction": {
        "tier": "Tier 2",
        "keyword": "inventory management for construction",
        "audience": "construction teams",
        "title": "Inventory Management for Construction | CountDepot",
        "description": "Track construction tools, materials, jobsite inventory, checkouts, and low-stock supplies.",
        "hero": "Inventory management for construction teams tracking tools, materials, and jobsites.",
        "pain": "Tools and materials move between trucks, shops, and jobsites, which makes manual tracking unreliable.",
        "use_cases": ["Track tools by jobsite or truck", "Check equipment out to crews", "Monitor consumables and materials", "Reserve items for upcoming jobs"],
    },
    "inventory-software-for-labs": {
        "tier": "Tier 2",
        "keyword": "inventory software for labs",
        "audience": "labs",
        "title": "Inventory Software for Labs | CountDepot",
        "description": "Track lab equipment, supplies, reagents, storage locations, and low-stock items affordably.",
        "hero": "Inventory software for labs tracking equipment, supplies, and storage locations.",
        "pain": "Labs need accurate supply visibility without forcing every team into an expensive enterprise platform.",
        "use_cases": ["Track equipment, supplies, and reagents", "Organize inventory by storage area", "Monitor low-stock items", "Record cost, vendor, and item details"],
    },
    "affordable-inventory-management": {
        "tier": "Tier 2",
        "keyword": "cheap inventory management software",
        "audience": "small teams",
        "title": "Affordable Inventory Management Software | CountDepot",
        "description": "Affordable inventory management software for small teams that need scanning, reservations, and item tracking.",
        "hero": "Affordable inventory management software without the bloated enterprise price.",
        "pain": "Small teams need inventory control, but many systems are priced for companies with larger budgets and dedicated admins.",
        "use_cases": ["Track items, quantities, costs, and locations", "Use barcode scanning from phones", "Reserve inventory before jobs", "Start simple and grow into advanced workflows"],
    },
    "free-inventory-management": {
        "tier": "Tier 2",
        "keyword": "free inventory management software",
        "audience": "teams starting out",
        "title": "Free Inventory Management Software | CountDepot",
        "description": "Start tracking inventory with CountDepot's free trial and simple small-business inventory workflow.",
        "hero": "Free inventory management trial for teams replacing spreadsheets.",
        "pain": "Teams often wait too long to leave spreadsheets because they do not want another expensive monthly tool.",
        "use_cases": ["Test inventory tracking before committing", "Import or add items gradually", "Use mobile scanning from the browser", "Upgrade only when the workflow proves value"],
    },
    "snipe-it-alternative": {
        "tier": "Tier 2",
        "keyword": "Snipe-IT alternative",
        "audience": "asset-tracking teams",
        "title": "Snipe-IT Alternative | CountDepot",
        "description": "A simple Snipe-IT alternative for teams that want hosted inventory, reservations, and phone scanning.",
        "hero": "A Snipe-IT alternative focused on simple hosted inventory and field scanning.",
        "pain": "Some teams want asset tracking without self-hosting, heavy setup, or IT-only workflows.",
        "use_cases": ["Track serialized assets and quantities", "Use phone-friendly scanning", "Reserve items for jobs or teams", "Manage non-IT inventory alongside assets"],
    },
    "fishbowl-alternative": {
        "tier": "Tier 2",
        "keyword": "Fishbowl alternative",
        "audience": "small operations teams",
        "title": "Fishbowl Alternative | CountDepot",
        "description": "A lightweight Fishbowl alternative for teams that need practical inventory tracking at a lower price.",
        "hero": "A Fishbowl alternative for teams that want useful inventory control without heavy implementation.",
        "pain": "Many small teams need visibility and accountability, not a large ERP project.",
        "use_cases": ["Track inventory across locations", "Monitor quantities and low stock", "Use reservations and checkouts", "Keep pricing and item history simple"],
    },
    "asset-panda-alternative": {
        "tier": "Tier 2",
        "keyword": "Asset Panda alternative",
        "audience": "asset-heavy teams",
        "title": "Asset Panda Alternative | CountDepot",
        "description": "A practical Asset Panda alternative for teams that need affordable inventory, asset tracking, and scanning.",
        "hero": "An Asset Panda alternative for teams that want simpler inventory and asset tracking.",
        "pain": "Asset-heavy teams need clear ownership, locations, and movement history without software that feels oversized.",
        "use_cases": ["Track assets and inventory together", "Scan from phones and tablets", "Reserve items before jobs", "See checkout and return history"],
    },
}


def seo_page_for_slug(slug):
    return SEO_PAGES.get(slug.strip("/"))


def seo_slugs():
    return tuple(SEO_PAGES.keys())
